project:
  type: website
  output-dir: docs

website:
  title: "Avalanche Forecasting"
  description: "Neural Network Avalanche Hazard Prediction for Scottish Mountains"
  favicon: "🏔️"
  
  navbar:
    background: "rgba(255, 255, 255, 0.95)"
    foreground: "#4a5568"
    right:
      - text: "Overview"
        href: "#overview"
      - text: "Data"
        href: "#data"
      - text: "Methodology" 
        href: "#methodology"
      - text: "Results"
        href: "#results"
      - text: "Conclusions"
        href: "#conclusions"

  page-footer:
    background: "#2d3748"
    foreground: "white"
    center: |
      Should we add our names somewhere here? Should i remove the link to where the original data can be found? | Data Science for Industry Assignment
      
      [📱 View on GitHub](https://github.com/yourusername/scottish-avalanche-prediction){.btn .btn-outline-light .btn-sm}
      [Scottish Avalanche Information Service](https://www.sais.gov.uk/){.btn .btn-outline-light .btn-sm}
      

format:
  html:
    theme: journal 
    css: styles.css 
    toc: false
    code-fold: true
    code-tools: true
    smooth-scroll: true
    anchor-sections: true
    link-external-newwindow: true
    
execute:
  freeze: auto
  cache: true