project:
  type: website
  output-dir: docs

website:
  title: "Avalanche Forecasting"
  description: "Neural Network Avalanche Hazard Prediction for Scottish Mountains"

format:
  html:
    theme: journal
    css: styles.css   
    toc: false
    code-fold: false
    code-tools: true
    smooth-scroll: true
    anchor-sections: true
    link-external-newwindow: true

execute:
  freeze: auto
  cache: true